# Welcome to Jekyll!
#

# Site settings
title: Victoria Parrish, Ph.D.
description: |
  Post-doctoral scholar in Experimental Particle Physics with the P-ONE and IceCube Experiments.
owner: Victoria Parrish # or company name
first_published: 2021 # if migrating another site, the year of your first publish
email: parrishv@msu.edu
baseurl: "" # the subpath of your site, e.g. /blog
social:
  github: https://github.com/vparrish
  linkedin-square: https://linkedin.com/in/victoria-parrish
  email: mailto:parrishv@msu.edu
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
